server:
  port: 9090

spring:
  application:
    name: admin-server
  security:
    user:
      name: admin
      password: admin
  cloud:
    config:
      uri: http://config-server:9296
  config:
    import: optional:configserver:http://config-server:9296

eureka:
  client:
    service-url:
      defaultZone: http://discovery-server:8761/eureka/
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
      base-path: /actuator
  endpoint:
    health:
      show-details: always

spring.boot.admin:
  context-path: /admin
  ui:
    title: Project Management Admin
    brand: Project Management
    base-url: /admin
  notify:
    filter:
      status-changes: WARNING,ERROR
